---

builds:
  -
    main: ./cmd/frontier
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags live
release:
  mode: keep-existing
